version: '3'

services:
  guf_donations:
    container_name: guf_donations
    build:
      dockerfile: docker/Dockerfile
      context: .
    init: true
    ports:
      - 8000:8000
    volumes:
      - db_data:/app/tracker_development/db
      - donation-tracker_static:/app/static
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - guf_tracker_dev
    depends_on:
      - db
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: guf_tracker
      MARIADB_DATABASE: guf_tracker
      MARIADB_USER: guf_tracker
      MARIADB_PASSWORD: guf_tracker
    networks:
      - guf_tracker_dev
    volumes:
      - ./mariadb:/var/lib/mysql

volumes:
  db_data:
  donation-tracker_static:

networks:
  guf_tracker_dev:
    name: guf_tracker_dev